### ISSUE TITLE
Bug: incorrect notification count

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#1056]
## Environment
iOS 16.2, icecubes 1.5.8

## Description
I have several accounts. If I receive new notifications for another account, I open the account menu and tap on the account which got notifications. I read the new notifications. I reopen the account menu and can see, that the notification count is not reset. Even switching to another account and switch back doesn’t reset the counter.

**Comment by rstockm** [comment]
Yes, the new multi-account notification system - as welcome as it is - needs some fine-tuning. Here are some reproducible bugs:

# App-Badge Count and multi-accounts

As of now, the App-Icon only shows a notification badge when the active account has new ones. Unread from other accounts are counted, bot not displayed for themself.
The scenario:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/3195116/221365694-297bb768-91b6-482c-a714-b9bf4a1e1387.png">

There are 4 notifications. 1 for the active account, 3 for another one. I start the app and navigate to activity:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/3195116/221365743-d6694863-b071-4a57-b1f0-8dae02abd9e4.png">

The activity-badge on the bottom for the active avvount is cleared, because I can just read the new entry - so far, so good. The other 3 notofocations lie under the Avatar on the upper left - so far, so good.
I exit the app, the now we see on the homescreen:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/3195116/221365848-26a0ee46-5bc8-4dd4-aecc-0810ca395a0a.png">

Hm. The 3 still unread notifications from account B are not displayed anymore. Now another notification for Account A arrives and:

<img width="421" alt="image" src="https://user-images.githubusercontent.com/3195116/221365887-a7fb612f-4753-45ba-8b4e-f369250cbd1d.png">

...and we're back to 4 again.

## expected behaviour:

The badge on the homescreen App-Icon should always display the sum of all unread notifications. In my caste 4 - 3 - 4.

# Latency of notifications badges when switching tabs

Scenarion: Active account A has 1 new notification. Account B has 3 other, older notifications. The homescreen shows:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/3195116/221366042-a4c91e43-c778-49c4-a250-619973f98037.png">

So far, so good. Now I enter the app, I left it on the activity tab. It looks like this:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/3195116/221366075-25dded9d-3ca7-405c-8149-ecccfaf1ff97.png">

Two problems: a) I can't figure out in this screen, how many/which notifications are new. This will be addressed in another feature-request soon. b) I now switch tab to home, and get:

<img width="418" alt="image" src="https://user-images.githubusercontent.com/3195116/221366165-e526387d-07eb-4680-b8ae-38fef52ffd1a.png">

This is plain wrong. The 4 is wrong in two ways: a) this shouldn't be the sum like on the homescreen, but only the notifications for the active account. and b) there ARE no new notifications for the active account - I was just there and read the 1 new.

## expected behavior

At all times, the notification badges should update in realtime for all accounts and all views/tabs. This will eat up some background activity, but "beeing up to date" is crucial. Right now, the user is in an constant "I'm missing out" state, which is no good UX.

**Comment by rstockm** [comment]
Update:

the release-notes of the 1.6 seem to address this, but this sequence still does not work:

- Account A: go to notifications tab, notifications are cleared (if there are any)
- Switch over to Account B
- Wait for some notifications of A to arrive
- Go to profile, the unread count reads (3) for example, switch to Account A
- The notifications view is loaded, the unread counter of the notifications tab shows no badge (which may be ok, for you are looking at the 3 new already)
- Switch to home tab
- Now the (3) badge arrives both on the notifications tab and the avatar-icon

So it's either too late or wrong at all to show the (3)

**Comment by Dimillian** [comment]
Yep, I plan to fix that. It's basically buggy if you switch account from the notifications tab.

**Comment by rstockm** [comment]
Hm - the count on the notification badge on the homescreen is still off, too - as described above
https://github.com/Dimillian/IceCubesApp/issues/1056#issuecomment-1445146289

**Comment by rstockm** [comment]
Yesterday i figured the 1.6.6 fixed this, but today I still see the same problem (switching away from the notification tab will get you wrong results if you come back from another account).

**Comment by blueturtleai** [comment]
Didn’t happen to me for a long time -> close
