### ISSUE TITLE
Bug: Mastodon streaming server received binary data.

### ISSUE THREAD

**Issue by shleeable** [Dimillian/IceCubesApp#1438]
## Environment:

aus.social streaming server is getting smashed by error connections from IceCubes.

## Description

`WARN socket Received binary data from 192.168.140.199 using IceCubesApp/1891 CFNetwork/1408.0.4 Darwin/22.5.0, closing connection`

**Comment by ThisIsMissEm** [comment]
Hey, I'm the developer working on the Mastodon side of the streaming server! 

There's a few things I note in your implementation that tie into the issue reported here:

1. In https://github.com/Dimillian/IceCubesApp/blob/9e01e6b0f691c2f5d641bd1b7e2815fcbca22d1a/Packages/Network/Sources/Network/Client.swift#L219 the current "protocol" is to send the OAuth token via the subprotocol field (second option to `UrlSession.websocketTask`), not sending it will result in issues of current versions that are configured to require authentication for streaming access. (In the next version of the protocol, which will be formally defined, the auth will be passed either in the connection URL string or in the subscribe message payload)
2. It seems like JSONEncoder is resulting in Data (binary) frames for websocket messages, when they should be text frames containing UTF-8 encoded JSON strings; from version 4.1.3 the code has been changed to reject connections sending binary messages (previously we tried to parse a binary message as utf-8 text)
3. You'll want to make sure you're sending ping frames regularly to ensure your connection is kept alive.
4. Please ensure you've a randomised jitter & exponential backoff algorithm for reconnecting, otherwIse you risk all clients reconnecting at once and overwhelming the instance's resources (thundering herd problem) when the streaming infrastructure is restarted or redeployed.

**Comment by shleeable** [comment]
![image](https://github.com/Dimillian/IceCubesApp/assets/17537000/c7d5834e-e922-4b01-b484-4c44aacbcb4e)

**Comment by Dimillian** [comment]
Thanks for all the detail. Will fix for the next update. Too bad I can’t send JSON data anymore. I guess I’ll just stringify it.

**Comment by ThisIsMissEm** [comment]
@Dimillian I'd also encourage you to add a maximum reconnection attempts before degrading & requiring user interaction to proceed with attempting to connect. Additionally, adding a jitter (random amount) to the retry delay will increase the likelihood of establishing a connection, as it means all clients won't be attempting to reconnect in the exact same timeframe, but instead be spaced out by 0 to the random millseconds amount
