### ISSUE TITLE
Bug:Switch between apps jump to the head

### ISSUE THREAD

**Issue by greyghoster** [Dimillian/IceCubesApp#1629]
## Environment:

iPhone 12 mini 

 - OS: 17.0.3

 - IceCubesApp version: 1.9.2

## Description

Switching from to another app and back sometimes causes Icecubes to jump to the head of the timeline.

**Comment by shanmukhateja** [comment]
I am also experiencing this issue.

### Steps to reproduce:

1. Open Ice Cubes and scroll down a few times.
2. Switch to a different app for a few seconds.
3. Switch back to Ice Cubes.

### Expected Output

My feed shouldn't reset to head.

### Actual Output

Feed jumps to the latest and now I have to scroll all the way down again.

### Note

This bug also happens when I open a link which launches System Browser.
It is not reproducible when I use in-app browser.

**Comment by shanmukhateja** [comment]
Solution:

Turn off "Fast Refresh" in Settings.

**Comment by greyghoster** [comment]
Unfortunately that doesn't work for me. I have "fast refresh" turned off and coming back from Firefox still resets to the head.
