### ISSUE TITLE
New posts button - don’t move position 

### ISSUE THREAD

**Issue by ToddHensley** [Dimillian/IceCubesApp#208]
When clicking the “New posts” button, I’d rather it didn’t jump to the top of the timeline. It should stay at the current position so I can scroll up through the new posts.

**Comment by nilrog** [comment]
Reported the same issue on Mastodon two days ago, before I found this tracker. And I hope this is fixed somehow, with a setting if someone prefers the current behavior. But the way it currently works is the opposite to, and unintuitive, way of all clients I have tried/used for Twitter and Mastodon. It feels just as bad as the curated timeline in Facebook/Twitter’s official apps. Even the official Mastodon app doesn’t throw away your position when new posts are found. In one way I think, since the posts are already loaded but not visible, that they should be present so you can just scroll up, and the button should be “Scroll to top”, since that is what it is actually doing.

**Comment by jtsom** [comment]
Came here to report the same. 

Also occurs when pulling to refresh to get new articles. Scrolls to the top and loses the position. 

What does the little button in the “new articles” button mean? Just show the next new item?

**Comment by pimoore** [comment]
Another vote from me, holding position in the timeline is really important.

**Comment by DanHulton** [comment]
Also came here to report this, but I'd even say that I'd be okay with it scrolling to the _start_ of new posts, as opposed to the _newest_ post.  As it is, I hit the button, get zoomed to the latest post, then have to scroll down to the first post I remember seeing (i.e. the start of new posts) in order to read in chronological order.

Specific use case that makes this really critical and not just a "nice to have" - any threads that you encounter when trying to read from the "top down" as it is right now are nonsensical, because you're getting them in reverse chronological order.  This means you have to manually scroll down _every time_ on the off chance you encounter a thread (or even content that requires being read in chronological order, like a series of reactions to an ongoing event from multiple people).

**Comment by dertuxmalwieder** [comment]
Another vote from me. IMO Woolly does that very well, maybe it could be an inspiration (which is why I have Woolly *and* IceCubes installed: Woolly is for reading, IceCubes is for writing).

Sometimes I have no time to check Mastodon for quite some time. I’d prefer to pick up where I left it instead of missing everything between then and now.

**Comment by steveinseabrook** [comment]
I find IceCubes to be very difficult to use the way it wants to display new posts.  It is critical that you do not lose your position when viewing new posts.  Otherwise, I love this app!

**Comment by Dimillian** [comment]
Don't worry guys, this will come :)

**Comment by logienick** [comment]
Please can I add my support for this request - It would be great to keep read posts location on timeline by default upon refreshing - or at the very least be able to return to that point easily after refresh... Many thanks!

**Comment by jtsom** [comment]
As an addition to this request - when switching accounts, currently the app will refresh for the new account and put me at the top of the list. Please remember the position in my posts when switching accounts! I always think I don't have anything new when I switch.
