### ISSUE TITLE
Bug: Images and videos not loading/displayed

### ISSUE THREAD

**Issue by ntadej** [Dimillian/IceCubesApp#2104]
## Environment:

 - OS: v17.5.1
 
 - IceCubesApp version: v1.10.42
 

## Description

After the latest update some media is not displaying/loading.

One example are some user avatars (see screenshot). The avatar is not there but if I click on it I get the full version fine.

![image](https://github.com/Dimillian/IceCubesApp/assets/805384/2a0219c3-e9e0-45c6-a9bd-b95646638712)

I also had issues playing some videos that work fine on the web. Not sure if it's some issue with mastodon.social though.

<!-- A clear and concise description of what the bug is.

**Comment by blueturtleai** [comment]
I experience the same problem with image loading since updating to 1.10.42. The problems playing videos is IMO not connected to the new version as I experience it already a long time.

Here is another example of images which are not loaded. The embedded image isn’t displayed, if I tap on it, it is displayed. If I check the posting on the website it is also shown.
https://botsin.space/@solarticker/112630433264725762

**Comment by SebaldJ** [comment]
Same problem with other profile pictures 

![image](https://github.com/Dimillian/IceCubesApp/assets/17111835/dc67c41a-9fe0-49c8-ac47-66c5c2a2f380)

![image](https://github.com/Dimillian/IceCubesApp/assets/17111835/7032c78b-997d-4212-acdb-40f53af63a78)

**Comment by blueturtleai** [comment]
The image display problem is fixed for me in 1.10.43.

**Comment by ntadej** [comment]
Same for me. Thanks!
