### ISSUE TITLE
Bug: missing posts in home timeline

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#635]
There was a gap of about 1 hour in my home timeline. As i were sure, that in the meantime some new posts must have arrived, I restarted the app. The new posts appeared afterwards.

iOS 16.2, icecubes 1.3.5

**Comment by adventure-tense** [comment]
I can confirm a similar experience where occasionally a post or two doesn't show up. 

Mastodon:
![image](https://user-images.githubusercontent.com/123326084/217368698-5e5383f0-9d57-4990-8094-d0a307484cd0.png)

Ice Cube:
![image](https://user-images.githubusercontent.com/123326084/217368838-9a678e95-d37b-4ce4-bdaf-1fd351f2019d.png)

**Comment by Dimillian** [comment]
Unfortunately Mastodon have only a 400 posts timeline for now. As the app don't have any background refresh for now, it's possible that some posts simply can't get loaded... but the limit will be raised to 800 soon on their backend.

**Comment by blueturtleai** [comment]
Do I understand it right, that the problem is you only can fetch 400 posts at once? I guess that’s the reason why other apps have a „load more posts“ button in their timeline.

Imo this is a better solution than fetching more at once because this will lead probably to performance issues.

**Comment by Dimillian** [comment]
There is not even a way to load this gap. You can try on the web or in the official app. Once you have a too big gap between your oldest top post and newer posts, you won't be able to see posts in between because the backend literally don't know anymore about it. You literally can't load more after 400 new posts (it'll be raised to 800 soon). The only way to have a full timeline is to store all of it client side, and then to do background fetching at regular interval to not leave a too long empty gap. This is something that Ivory do and that I'll explore at some point.

**Comment by blueturtleai** [comment]
Okay, I see. So, the API doesn’t allow to fetch for example the next 400 starting with post 400?

**Comment by Dimillian** [comment]
Exactly. Because they don't store (for now) more than 400.

**Comment by blueturtleai** [comment]
Seems to be caused by the limitation of the API and didn’t occur anymore.
