### ISSUE TITLE
Feature request: Filter by language

### ISSUE THREAD

**Issue by RockyC36** [Dimillian/IceCubesApp#752]
I’d like the ability to only show posts in languages that I can read.

**Comment by phpmacher** [comment]
You can configure that in your instance under: "/settings/preferences/other"

I think, nearly all clients use this setting.

**Comment by sothawo** [comment]
That's a server setting. The problem is, that often people when posting don't set the language of their post in case it is different from their default setting. I for example have it set to english, german and french, but I see posts in other languages because the poster uses a different language and does not set it when posting.

**Comment by RockyC36** [comment]
That explains a lot! Thanks!

--

**Comment by phpmacher** [comment]
so i think, this ticket could be closed!?

**Comment by RockyC36** [comment]
YES!

--
