### ISSUE TITLE
[Bug] Search is not working properly for me

### ISSUE THREAD

**Issue by btylerh7** [Dimillian/IceCubesApp#78]
I am having a lot of issues with the search feature. I tried to get as many videos as I could. 

The app seems to crash a lot for me when loading search results:
https://user-images.githubusercontent.com/91493312/212547402-db4e13dc-c037-48b8-8dcb-a6bee56c0281.MOV

Sometimes when I type the cursor position randomly changes:
https://user-images.githubusercontent.com/91493312/212547441-10810e2b-480c-4b59-af83-79d9393cac79.MOV

Not sure what the issue is with this one, but the Japanese keyboard doesn't seem to be working properly. I haven't had this happen anywhere else. But it does not display autocomplete suggestions, which is really important for Japanese. 
https://user-images.githubusercontent.com/91493312/212547548-91ef870d-c433-44bd-81af-ce280023d3e8.MOV

**Comment by Dimillian** [comment]
@EvilOne The search could also use a debounce, that might the issue for the cursor position. I saw that too for me. For the Japanese keyboard I'll look.

**Comment by EvilOne** [comment]
@Dimillian I can look into that as a part of #79 or start a new PR.

**Comment by Dimillian** [comment]
I think it could be good in #79, thanks a lot!

**Comment by EvilOne** [comment]
OK, will do!

**Comment by pacorob** [comment]
I hope this gets fixed since it quite often keeps loading when opening the 'Explore' (Search) tab without even having entered anything in the search itself. You would expect to see the 'Trending tags' and 'Suggested users' , 'Trending posts' immediately but these only appear after searching a term e.g. 'iOS' and then removing this search.
