### ISSUE TITLE
Feature request: make text of post selectable 

### ISSUE THREAD

**Issue by blueturtleai** [Dimillian/IceCubesApp#817]
Please make the text of a post selectable so it can be copied. I know, that I can copy the whole text. But often I want to look up a single word and it’s much easier if I can just select and copy that word.

**Comment by Dimillian** [comment]
This is sooooooo stupid because of SwiftUI. Believe me, I want to do it. But this is just impossible because of SwiftUI... I'll dig into a "hacky" solution at some point.

**Comment by blueturtleai** [comment]
Okay, I see. It‘s not super important for me, just sometimes a bit annoying. More important would be #245 😉.

**Comment by AlanQuatermain** [comment]
Have you tried `View.textSelection(.enabled)`? Is there something causing that to be ineffective?

**Comment by Dimillian** [comment]
Two things: 
* It conflict with context menu. 
* It not really text selection in SwiftUI, it just allow a basic copy / share menu on the whole text sadly.

**Comment by AlanQuatermain** [comment]
Ah yeah, I see that now. The iOS version just gives each `Text` instance a popup menu, which is disappointing. It works as expected on macOS though—but that's only if you build a full Mac app, rather than going through Apple Silicon or Catalyst. It's a lot easier to make it work on the Mac because of how text editing is implemented there (AppKit uses a shared 'field editor' view/window hovering above the NSTextView, which SwiftUI can provide pretty easily; in UIKit more of it is implemented by UILabel and friends, which SwiftUI isn't usually using).

**Comment by Dimillian** [comment]
I'm glade the underlying of SwiftUI are slowly moving away from UIKIt but some components are so lacking for now. Text have a lot of shortcomings, and wiring up a UILabel / UITextView for the timeline / status row would be a pain as the layout have to be done manually. Really stuck on this one for now :(

About proper macOS app: I do want to get there at some point. If you enable Catalyst for this app it's already a lot better than just the iOS app on Apple Silicon.

**Comment by AlanQuatermain** [comment]
Yeah, I've been playing around with that. I've got a bunch of the packages building directly for macOS, but someone keeps going & putting in upstream changes all the time which makes it difficult to keep up 😜

This is actually a very nicely architected application, I've been very impressed by it. There are a few things I think could make for good optimizations, and I'm going to try those out & hopefully provide a PR to that effect. If they work as well as I hope, it'd actually make a good case study for SwiftUI architecture and optimization techniques & best practices.

**Comment by Dimillian** [comment]
Now I'm very curious. I promise I'm done with big changes... for now

**Comment by phpmacher** [comment]
@Dimillian Maybe you can show a text popup in longpress on iOS, from which you can select text?

Just as an idea...

**Comment by iWoodsman** [comment]
Text select is worth fighting for, if a solution can be found. Some users intentionally type in URLs without the scheme prepended, to defeat single-click propagations, a very Fediverse-minded attitude. But this relies on everyone being able to lift the URL out and paste into browser.
My workaround now is to screenshot the post, save the picture into a note, view that and use iOS select-text-in-image to lift out the text and paste to browser. Nifty but gets old fast.

**Comment by blueturtleai** [comment]
Fixed in version 1.9.x.

**Comment by phpmacher** [comment]
@blueturtleai What do you mean with "fixed in version 1.9.x"?

There is a Menu-Point in the Menu that appears, if i click the three dots of a post, where i can open the text in a new area, where i can select text. That seems IMHO very unhandy and not very intuitiv.

If this menu-point at least would appear, if you longpress a post, that would be much more useful IMHO.

I don't think, this is closed.

**Comment by blueturtleai** [comment]
For me the issue is closed, as I can select text now. You are right, that it's not very handy to reach this functionality. I'd suggest, that you open a new change issue where you can make a suggestion for better usability.
