### ISSUE TITLE
Feature request: Dutch language improvement

### ISSUE THREAD

**Issue by RobHomey** [Dimillian/IceCubesApp#896]
The accounts you are following is named in the pull-down “Start” (Dutch language). I do not understand way this word has been chosen. It is a list of people you are following. In Dutch is the right name should be: Volgend
Maybe “Start” can be changed into “Volgend” in a next release.

**Comment by icod** [comment]
Not sure if this is a localization issue. 

The term "Start" was chosen because it is the home of the app: that's what it's called in the English localization and it has this little house icon. 

I agree, that maybe Home (or "Start" for that matter) doesn't _quite_ capture the meaning of that view, because it shows posts by the people you follow. 

So changing this to "Volgend" _just for the Dutch localization_ doesn't sound like the solution to me.
