### ISSUE TITLE
Run as a macOS app

### ISSUE THREAD

**Issue by makhocheung** [Dimillian/IceCubesApp#92]
Hello, how can I run the project targeted on Mac? It seems the IceCubesApp target doesn't support Mac.

**Comment by Dimillian** [comment]
Only if you have Apple Silicon (M1 / M2)

**Comment by makhocheung** [comment]
I did. I only find the `My Mac(Designed for iPad)`
![image](https://user-images.githubusercontent.com/22256775/213097230-1b88d83b-c33d-45b3-a4d0-a23a75f1d55b.png)

**Comment by Dimillian** [comment]
It is the macOS target! This is my choice to run the app on macOS. It run the iPad app. No specific macOS target.

**Comment by makhocheung** [comment]
OK, get it.

**Comment by stuffmc** [comment]
Since you use SwiftUI, Apple itself recommends to make a specific Mac App, not an iPad App running on macOS. I tried it, was stuck with dependencies, but you should be able to fix this easily. I used to have a M1 Mac, but I'm back on the last 16" MBP Intel. Of course I tried to support 10.15 but it would be totally cool for me if you only support macOS 13 Ventura. I was just trying to see how to get rid of the dependency problems and 10.15 sees like an option, although if you use recent SwiftUI you probably won't be able to support 10.15 or even 11 or 12. It would be great to support Intel Macs as well.

```
EmojiText
The package product 'Nuke' requires minimum platform version 10.15 for the macOS platform, 
but this target supports 10.13
```

**Comment by Dimillian** [comment]
There is so many consideration when building a proper macOS app. I'm not at the stage yet. I like that it's just the same app for now. It's a side project, I don't have enough time to maintain two separates app. I might do a Catalyst build tho, because it's 99% ISO and working better than the iOS app on Apple Silicon.
