### ISSUE TITLE
Bug: 2 bugs with messages with multiple photos

### ISSUE THREAD

**Issue by alexelgt** [Dimillian/IceCubesApp#965]
## Environment:

 - OS: 
 iPad OS 16.3.1
 - IceCubesApp version: 
 V1.5.4

## Description

I’ve found these 2 bugs when there is a message with multiple images:

- If you tap a photo, an incorrect photo is shown. Example: if you tap the first photo, the third one is shown.
- If you tap a photo, tap on the photo list (icon a the top left), choose another photo and go back to the message, the whole app becomes unresponsive.

https://user-images.githubusercontent.com/24291435/220177394-ee42e7e1-5038-4364-8468-b815a9f099fd.MOV

**Comment by JulianKahnert** [comment]
Hi @Dimillian,

I can reproduce this bug! It occurs every time, when I open an image in this [toot](https://mastodon.social/@deanatoire/109904713207900051) AND when I open the list in the leading navBar!
When I don’t open the list via the navBar it works perfectly!

**Comment by Dean151** [comment]
@Dimillian I've reproduced and analyzed the bug. It's a frame issue!
The Image is clipped ; but still have the "tapGesture target" above the others.
That's why for vertical images, third and forth images have priority on first or second. 
And for horizontal images, second and forth have priority on first and third.

Contact me on Slack if you need more info ;)

**Comment by JulianKahnert** [comment]
Hi @Dean151,
I've created #991 to fix the issue. Would you like to code review it? 🙂
